services:
  - type: web
    name: my-nextjs-app
    env: node
    buildCommand: "npm ci && npm run build"
    startCommand: "npm run start"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
